version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api: 
    build:
      dockerfile: Dockerfile
      context: './backend'
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=postgres
      - DB_HOST=postgres
      - PORT=5314
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app